//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by GSPlayer2.rc
//
#define IDS_FILTER_OPEN_FILE            1
#define IDS_FILTER_OPEN_FILE2           2
#define IDS_TITLE_OPEN_FILE             3
#define IDS_TITLE_ADD_FILE              4
#define IDS_TITLE_FIND_FILE             5
#define IDS_TITLE_SAVE_LIST             6
#define IDS_FILTER_SAVE_LIST            7
#define IDS_TITLE_EQ                    8
#define IDS_TITLE_EFFECT                9
#define IDS_TITLE_BASSBOOST             10
#define IDS_FMT_DISP_INFO               14
#define IDS_FMT_DISP_VOLUME             15
#define IDS_TITLE_SKIN_FILE             16
#define IDS_FILTER_SKIN_FILE            17
#define IDS_MSG_CONNECTING              18
#define IDS_FMT_BUFFERING               19
#define IDS_FMT_BUFINFO                 20
#define IDS_FMT_DEL_PRESET              22
#define IDS_TITLE_DEL_PRESET            23
#define IDM_TOOL_TOGGLEDISPLAY          100
#define IDI_MAIN                        101
#define IDM_SHOW_MENU                   101
#define IDR_MENU                        102
#define IDR_POPUP                       102
#define IDM_MENU                        102
#define IDD_ABOUT_DLG                   103
#define IDD_PAGE_PLAYER                 104
#define IDD_LOCATION_DLG                106
#define IDM_TOOL_VOLUP                  108
#define IDM_TOOL_VOLDOWN                109
#define IDR_MAIN                        113
#define IDD_PRESETNAME_DLG              120
#define IDB_VOLSLIDER                   121
#define IDB_VOLTRACK                    122
#define IDB_BUTTON_PUSH                 123
#define IDB_BUTTON_NORMAL               124
#define IDD_SLEEPTIMER_DLG              127
#define IDB_NUMBER                      129
#define IDD_DIALOG1                     129
#define IDD_OPTION_DLG                  129
#define IDD_OPTIONS_DLG                 129
#define IDB_STATUS                      130
#define IDR_DONE                        130
#define IDB_BUTTON                      131
#define IDR_FOLDERDLG                   131
#define IDB_PLAYOPTION                  132
#define IDD_EFFECT_DLG                  133
#define IDI_ROOT                        134
#define IDD_FOLDER_DLG                  146
#define IDD_PAGE_PLUGIN                 149
#define IDR_DIALOG                      151
#define IDD_KEYCTRL_DLG                 152
#define IDD_PAGE_STREAMING              175
#define IDD_PAGE_DECODER                176
#define IDD_PAGE_ASSOCIATE              177
#define IDD_PAGE_SKIN                   178
#define IDD_PAGE_DISPLAY                180
#define IDI_FILE                        200
#define IDC_EDIT_BUFF                   1000
#define IDC_EDIT_PREBUFF                1001
#define IDC_SPIN_OUT_BUFF_LEN           1001
#define IDC_SPIN_BUFF                   1002
#define IDC_SPIN_OUT_PREBUFF            1002
#define IDC_EDIT_LOCATION               1002
#define IDC_SPIN_PREBUFF                1003
#define IDC_UP                          1004
#define IDC_LIST_PREAMP                 1004
#define IDC_CHECK_3DCHORUS              1005
#define IDC_CHECK_PROXY                 1005
#define IDC_CHECK_SCROLLTITLE           1005
#define IDC_CHECK_AUTOON                1005
#define IDC_CHECK_SCANCOMPLETELY        1005
#define IDC_TREE_FOLDER                 1005
#define IDC_DOWN                        1006
#define IDC_SPIN_PREAMP                 1007
#define IDC_SPIN_BASSBOOST              1008
#define IDC_LIST_BASSBOOST              1009
#define IDC_CMB_AUTOOFF                 1010
#define IDC_LIST_SURROUND               1010
#define IDC_SPIN_SURROUND               1011
#define IDC_CMB_LOCATION                1012
#define IDC_LIST_3DCHORUS               1012
#define IDC_SPIN_3DCHORUS               1013
#define IDC_CHECK_PREAMP                1014
#define IDC_LIST_REVERB                 1015
#define IDC_EDIT_PROXY                  1016
#define IDC_SPIN_REVERB                 1016
#define IDC_CHECK_ENABLE_BATTERY        1017
#define IDC_CHECK1                      1017
#define IDC_CHECK_USESYSVOLUME          1017
#define IDC_CHECK_SUBFOLDER             1018
#define IDC_LIST_ECHO                   1018
#define IDC_LIST_PAGES                  1018
#define IDC_SPIN_ECHO                   1019
#define IDC_EDIT_NAME                   1022
#define IDC_CHECK_POWEROFF              1027
#define IDC_TITLE                       1029
#define IDC_CHECK_OUTPUT_FADE           1030
#define IDC_CHECK_SURROUND              1031
#define IDC_CHECK_REVERB                1032
#define IDC_CHECK_BASSBOOST             1033
#define IDC_CHECK_RESUME                1036
#define IDC_CHECK_PLAYONSTART           1037
#define IDC_CHECK_TRAYICON              1038
#define IDC_CHECK_ECHO                  1040
#define IDC_EDIT_FILE                   1040
#define IDC_BROWSE                      1041
#define IDC_CHECK_ALWAYSOPENDEV         1042
#define IDC_CHECK_EQUALIZER             1043
#define IDC_CHECK_TIMER                 1047
#define IDC_STATIC_UP                   1048
#define IDC_EDIT_OUT_BUFF_LEN           1049
#define IDC_STATIC_DOWN                 1049
#define IDC_EDIT_OUT_PREBUFF            1050
#define IDC_STATIC_LEFT                 1050
#define IDC_STATIC_RIGHT                1051
#define IDC_STATIC_CENTER               1052
#define IDC_CHECK_PEEK                  1069
#define IDC_CHECK_SUPZERO               1069
#define IDC_CHECK_SAVE_DEFLIST          1070
#define IDC_CHECK_ADD_EXISTING          1071
#define IDC_EDIT_TIMER                  1076
#define IDC_SPIN_TIMER                  1078
#define IDC_STATIC_BUFINFO              1079
#define IDC_LIST_EXT                    1080
#define IDC_CHECK_ALL                   1081
#define IDC_CLEAR_ALL                   1082
#define IDC_CONFIG                      1083
#define IDC_LIST_PLUGIN                 1084
#define ID_KEY_RETURN                   1100
#define ID_KEY_LEFT                     1101
#define ID_KEY_UP                       1102
#define ID_KEY_RIGHT                    1103
#define ID_KEY_DOWN                     1104
#define ID_KEY_BTN1                     1105
#define ID_KEY_BTN2                     1106
#define ID_KEY_BTN3                     1107
#define ID_KEY_BTN4                     1108
#define ID_KEY_BTN5                     1109
#define ID_KEY_BTN6                     1110
#define ID_KEY_REMBTN1                  1111
#define ID_KEY_REMBTN2                  1112
#define ID_KEY_REMBTN3                  1113
#define ID_KEY_REMBTN4                  1114
#define ID_KEY_REMBTN5                  1115
#define ID_KEY_REMBTN6                  1116
#define ID_KEY_REMBTN7                  1117
#define ID_LIST_SELECTIONMODE           32771
#define IDM_FILE_SELMODE                32772
#define IDM_SUBDIR                      32773
#define IDC_CTRLKEY                     32807
#define IDM_OK                          40001
#define IDM_FILE_SAVE_LIST              40001
#define IDM_FILE_ADD                    40002
#define IDM_HELP_ABOUT                  40003
#define IDM_APP_EXIT                    40004
#define IDM_FILE_FIND                   40008
#define IDM_TOOL_EFFECT                 40009
#define IDM_TOOL_OPTION                 40010
#define IDM_FILE_OPEN_LOCATION          40011
#define IDS_MAIN                        40012
#define IDM_FILE_LIST                   40015
#define IDM_PLAY_REPEAT                 40016
#define IDM_PLAY_SHUFFLE                40017
#define IDM_FILE_OPEN                   40018
#define IDM_TOOL_TOPMOST                40020
#define IDS_KEY                         40022
#define IDM_DELETE_KEYMAP               40025
#define IDM_PLAY_PLAYPAUSE              40027
#define IDS_TRAY                        40032
#define IDM_APP_SHOWHIDE                40034
#define IDM_FILE_SORT_BYPATH            40035
#define IDM_PLAY_STOP                   40036
#define IDM_PLAY_PREV                   40037
#define IDM_PLAY_NEXT                   40038
#define IDS_DUMMY                       40043
#define IDC_SAVE                        40044
#define IDM_PLAY                        40049
#define IDM_TOOL                        40050
#define IDM_FILE_DELETE                 40051
#define IDM_FILE_DOWN                   40052
#define IDM_FILE_UP                     40053
#define IDM_PLAY_REPEAT_NONE            40054
#define IDM_PLAY_REPEAT_ALL             40055
#define IDM_PLAY_REPEAT_ONE             40056
#define IDM_FILE_DELETEALL              40063
#define IDS_LIST_SEL0                   40068
#define IDM_PLAY_SELECTED               40069
#define IDS_LIST_SEL1                   40071
#define IDM_FILE_SORT_BYNAME            40072
#define IDM_TOOL_SLEEPTIMER             40073
#define IDM_PLAY_REW                    40074
#define IDM_PLAY_FF                     40075
#define IDM_LIST                        40076
#define IDS_KEY_COLUMN_KEY              40080
#define IDS_KEY_COLUMN_COMMAND          40081
#define IDS_TITLE_PREVIEW               40082
#define IDS_FMT_DISPLAY_AUTOOFF_NONE    40083
#define IDS_FMT_DISPLAY_AUTOOFF         40084
#define IDS_ROOT_FOLDER_NAME            40085
#define IDM_TOOL_KEYCTRL                40086
#define IDS_NOTIFY_TITLE                40086
#define IDM_TOOL_HOLD                   40087
#define IDS_MSG_HOLD_ON                 40088
#define IDS_MSG_HOLD_OFF                40089
#define IDM_TOOL_HOLDDISP               40090
#define IDM_PLAY_PLAYSTOP               40091
#define IDS_FILTER_OPEN_ALL             40092
#define IDS_FILTER_OPEN_SUPPORTED       40093
#define IDS_FILTER_OPEN_INTERNAL        40094
#define IDS_FMT_NULL_FILE_TYPE          40095
#define IDSOK                           40096
#define IDSCANCEL                       40097
#define IDM_MAIN                        40098
#define IDSDONE                         40098
#define IDM_TRAY                        40099
#define IDM_LIST_SEL0                   40100
#define IDS_OPTION_PLAYER               40100
#define IDM_LIST_SEL1                   40101
#define IDS_OPTION_DECODER              40101
#define IDM_KEY                         40102
#define IDS_OPTION_STREAMING            40102
#define IDS_OPTION_ASSOCIATE            40103
#define IDS_OPTION_DISPLAY              40104
#define IDS_OPTION_SKIN                 40105
#define IDS_OPTION_PLUGIN               40106
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         32773
#define _APS_NEXT_CONTROL_VALUE         1019
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
